services:
  web:
    image: node:22
    working_dir: /app
    ports:
      - "8005:3000"
    volumes:
      - ./:/app
    env_file:
      - path: .env.local
        required: false
      - path: .env
        required: false
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
    command: sh -c "npm install --legacy-peer-deps && npx next build && npm start"
