services:
  web:
    image: node:latest
    working_dir: /app
    ports:
      - "8004:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    command: sh -c "npm install --legacy-peer-deps && npx next dev --hostname 0.0.0.0 --port 3000 --no-turbopack"
